### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true # automatically start the local network container, if not already running

[[development.accounts]]
name = "me" # Required. Keys for this account will be saved to `./.stellar/identity`

[development.contracts]
nft_sequential_minting_example = { client = true, constructor_args = "--owner me --name 'Importantdocs' --uri 'myURI' --symbol 'IDOC'" }

[development.contracts.squares_gallery]
client = true
# Update the WASM hash below to match the hash of your built and uploaded contract.
constructor_args = "--owner me --nft_wasm_hash 88ff6a485f04ece39f8538dbb27f09b97e6e5383f6d49dad5dae026d6aa9f83c --xlm_sac $(stellar contract id asset --asset native)"
after_deploy = """
deploy_collection --base_uri "https://example.com/mynft/" --name "Squares Gallery" --symbol "SSQ" --collection_size 20 --item_price 10000000
"""

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]
nft_sequential_minting_example = { id = "CDAYJ2PHA7VROYLWCPKHNRG5OK553VJYZ473K72REL2BKARCUNPLJD6O" }
squares_gallery = { id = "CA2A3HR5HZGVVSC4CX25V4FS36OSU3JKPHWHKORYK3RHP23R6TGA4YYY" }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "gallery-mainnet"
default = true

[production.contracts]
nft_sequential_minting_example = { id = "TODO"}
squares_gallery = { id = "TODO" }
